### ISSUE TITLE
hdr_to field not big enough

### ISSUE THREAD

**Issue by cjpf** [cjpf/barracuda-syslog-api#10]
mail-api_1   | Job "job1 (trigger: cron[day_of_week='*', hour='*', minute='2,5,8,11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59'], next run at: 2020-03-20 18:14:00 UTC)" raised an exception
mail-api_1   | Traceback (most recent call last):
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
mail-api_1   |     self.dialect.do_execute(
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
mail-api_1   |     cursor.execute(statement, parameters)
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
mail-api_1   |     result = self._query(query)
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
mail-api_1   |     conn.query(q)
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
mail-api_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
mail-api_1   |     result.read()
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
mail-api_1   |     first_packet = self.connection._read_packet()
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
mail-api_1   |     packet.check_error()
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
mail-api_1   |     err.raise_mysql_exception(self._data)
mail-api_1   |   File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
mail-api_1   |     raise errorclass(errno, errval)
mail-api_1   | pymysql.err.DataError: (1406, "Data too long for column 'hdr_to' at row 1")
mail-api_1   | 
mail-api_1   | The above exception was the direct cause of the following exception:

mail-api_1   | [parameters: {'message_id': '1584499446-893441-30813-24222-1', 'account_id': 'ESS59024', 'domain_id': '131649', 'src_ip': '209.85.210.48', 'ptr_record': 'mail-ot1-f48.google.com', 'hdr_from': 'Joe Gorman <joegorman@comcast.net>', 'env_from': 'mike.gorman87+caf_=gmail=cudaseteam.us@gmail.com', 'hdr_to': 'Mike Gorman <mike.gorman87@gmail.com>, .Glenn - Hawk Schussman <glennschussman@ymail.com>, .Nancy Elton <nancyelton@comcast.net>, .Larry & Merja Bliss <rktec33@earthlink.net>, .Larry Wolfe <Larry@midwestcolorlab.com>, .Miriam Wettenstein <dimensionalmktg@aol.com>', 'dst_domain': 'cudaseteam.us', 'size': 4334214, 'subject': 'FW: FINALLY something to laugh about', 'timestamp': '2020-03-18T02:44:13+0000'}]

**Comment by cjpf** [comment]
4b1071425eab8137a78066c0285ce57b6fe59e2c
